### PR TITLE
Coding review

### PR DESCRIPTION
**Pull request by muhenge**
This pull request is for coding review

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Awesome :+1: @muhenge 
Your clone looks good and meets most requirements. However, we can't merge yet. Work on the following requirements;
- [ ] fix stickler errors
- [ ] remove horizontal scroll bar from your page
- [ ] remove comments from your code especially from ```style.css```
- [ ] make your README more professional

### Make the changes and re-submit for another review.

**Review by Redvanisation — CHANGES_REQUESTED** [review]
### Hello @muhenge  🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. Add margin-top to the main text, it should be spaced out from the navbar on top.
2. Wrap the main content of the website in a `<main>` tag.
3. Validate and fix the HTML markup [here](https://validator.w3.org/#validate_by_input)
4. Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by ebukaume** [comment]
Hi @muhenge :wave: 

Nice job implementing the requested changes. Everything **(almost)** looks good, but there is an issue with your navbar.

You seem to have thrown away the `iPhone` button. If this were to be an enterprise website, it means our users would no longer know about our dear `iPhone`. So you see, it is important you add it.

Also, what the @Redvanisation meant by `Wrap the main content of the website in a <main> tag` is so you have a structure like:

`<header></header>`
`<main></main>`
`<footer></footer>`

Fix that also. Kindly, submit another code review request after making **those changes**.

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by muhenge** [comment]
> Hi @muhenge wave
> 
> Nice job implementing the requested changes. Everything **(almost)** looks good, but there is an issue with your navbar.
> 
> You seem to have thrown away the `iPhone` button. If this were to be an enterprise website, it means our users would no longer know about our dear `iPhone`. So you see, it is important you add it.
> 
> Also, what the @Redvanisation meant by `Wrap the main content of the website in a <main> tag` is so you have a structure like:
> 
> `<header></header>`
> `<main></main>`
> `<footer></footer>`
> 
> Fix that also. Kindly, submit another code review request after making **those changes**.
> 
> Happy Coding v
> **Ebuka Umeokonkwo**
> [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

Thank you for your advice, I need some clarification about the apple button in the nav you mentioned, is it the apple logo?

**Review by whiz25 — APPROVED** [review]
## Good job :clap: 
Please go ahead and merge. I wish you success in your upcoming projects.
Use ```Martin Afani``` when filling the form.

**Comment by muhenge** [comment]
# Build with background and gradients 
### marging to the master branch 
[the preview](https://muhenge.github.io/apple-clone/#)

**Pull request merged**
